apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ape-java-springboot 
  janus-idp.io/tekton: ape-java-springboot
  backstage.io/kubernetes-id: ape-java-springboot
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: ape-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  