apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ape-java-springboot
  janus-idp.io/tekton: ape-java-springboot
  backstage.io/kubernetes-id: ape-java-springboot
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: ape-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
